name: Android Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          distribution: adopt
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew build